s

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,31 +1,42 @@
 #!/usr/bin/env bash
 
-BUILD_DIR=/app/libpostal
-CACHE_DIR=$2
 
-mkdir -p $BUILD_DIR
-mkdir -p $CACHE_DIR
 
-echo $BUILD_DIR
-echo $CACHE_DIR
 
-echo "-----> Installing libpostal"
+set -e
 
-git clone https://github.com/openvenues/libpostal
+
+
+build=$1
+cache=$2
+
+mkdir -p $build
+mkdir -p $cache
+
+cd $cache
+
+echo "-----> Downloading snappy"
+wget https://codeload.github.com/google/snappy/tar.gz/1.1.3 -O snappy.tar.gz
+tar -zxvf snappy.tar.gz
+cd snappy-1.1.3
+./autogen.sh
+./configure --prefix=/app/snappy
+make
+make install
+cd -
+echo "-----> Downloading libpostal"
+
+git clone https://github.com/openvenues/libpostal --depth 1
 cd libpostal/
-echo "        Bootstrap"
 ./bootstrap.sh
-./configure --prefix=/app/libpostal --datadir=$BUILD_DIR
+LDFLAGS="-L$build/lib" CFLAGS="-I$buildinclude" PKG_CONFIG_PATH="$build/lib/pkgconfig" ./configure --prefix=/app/libpostal --datadir=$build
+cp ~/vendor/include/snappy* .
 
-echo $BUILD_DIR
-echo $CACHE_DIR
-
-echo "        Make"
 make -j4
-echo "        Make install"
+make install
 make install
 
-echo "        DONE ✅"
+mv /app/snappy /app/libpostal $build
+# curl --fail --retry 3 --retry-delay 1 --connect-timeout 3 https://s3.amazonaws.com/toolsbucket/vendor.tar.bz2 -s -o - | tar jvxf - -C vendor/
 
-echo $BUILD_DIR
-echo $CACHE_DIR
+#profile.d script -> downloads the data.
